/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  librarySidebar: [
    'intro',
    {
      type: 'category',
      label: 'Personal',
      collapsed: false,
      items: [
        'Personal/mbti',
        'Personal/chinavisa',
        'Personal/poke',
        {
          type: 'category',
          label: 'Cars',
          items: ['Personal/Cars/lexus-rx350-ac-flow-sensor'],
        },
        {
          type: 'category',
          label: 'Hobbies & Collections',
          items: [
            'Personal/Hobbies/shoes',
            'Personal/Hobbies/redwing',
            'Personal/Hobbies/discussion',
            'Personal/Hobbies/aeron',
            'Personal/Hobbies/herman',
            'Personal/Hobbies/handbag',
            'Personal/Hobbies/key',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Home & Family',
      collapsed: false,
      items: [
        'Property/home',
        'Property/contract',
        'Family/bloomber',
        'Family/colombia',
        'Finance/financial',
        'Legal/readme',
      ],
    },
    {
      type: 'category',
      label: 'Technology & Homelab',
      collapsed: false,
      items: [
        'Work & Career/tim',
        'Work & Career/virtualize',
        'Work & Career/ssl',
        'Work & Career/sas',
        'Work & Career/Project/moa',
        {
          type: 'category',
          label: 'Homelab Infrastructure',
          items: [
            'Work & Career/Homlab/dashboard',
            'Work & Career/Homlab/proxmox',
            'Work & Career/Homlab/storage',
            'Work & Career/Homlab/truenas',
            'Work & Career/Homlab/r720',
            'Work & Career/Homlab/dell',
            'Work & Career/Homlab/h710',
            'Work & Career/Homlab/idrac',
            'Work & Career/Homlab/pci',
            'Work & Career/Homlab/qsfp',
            'Work & Career/Homlab/ds4246',
            'Work & Career/Homlab/netapp',
            'Work & Career/Homlab/samba',
            'Work & Career/Homlab/rancher2',
            'Work & Career/Homlab/systemtesting',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Career & Learning',
      collapsed: false,
      items: [
        'Work & Career/ea',
        'Work & Career/leader',
        'Work & Career/code',
        'Work & Career/mnit',
        'Work & Career/forbe',
        'Work & Career/qiu',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: false,
      items: ['Reference/cellphone', 'Reference/media'],
    },
  ],
  techSidebar: [
    'Work & Career/tim',
    'Work & Career/virtualize',
    'Work & Career/ssl',
    'Work & Career/sas',
    'Work & Career/Project/moa',
    {
      type: 'category',
      label: 'Homelab Infrastructure',
      items: [
        'Work & Career/Homlab/dashboard',
        'Work & Career/Homlab/proxmox',
        'Work & Career/Homlab/storage',
        'Work & Career/Homlab/truenas',
        'Work & Career/Homlab/r720',
        'Work & Career/Homlab/dell',
        'Work & Career/Homlab/h710',
        'Work & Career/Homlab/idrac',
        'Work & Career/Homlab/pci',
        'Work & Career/Homlab/qsfp',
        'Work & Career/Homlab/ds4246',
        'Work & Career/Homlab/netapp',
        'Work & Career/Homlab/samba',
        'Work & Career/Homlab/rancher2',
        'Work & Career/Homlab/systemtesting',
      ],
    },
  ],
  careerSidebar: [
    'Work & Career/ea',
    'Work & Career/leader',
    'Work & Career/code',
    'Work & Career/mnit',
    'Work & Career/forbe',
    'Work & Career/qiu',
  ],
  personalSidebar: [{ type: 'autogenerated', dirName: 'Personal' }],
  homeSidebar: [
    {
      type: 'category',
      label: 'Property',
      items: ['Property/home', 'Property/contract'],
    },
    {
      type: 'category',
      label: 'Family',
      items: ['Family/bloomber', 'Family/colombia'],
    },
    'Finance/financial',
    'Legal/readme',
    {
      type: 'category',
      label: 'Reference',
      items: ['Reference/cellphone', 'Reference/media'],
    },
  ],
};

export default sidebars;
