/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  lifeSidebar: [{ type: 'autogenerated', dirName: 'life' }],
  personalSidebar: [{ type: 'autogenerated', dirName: 'Personal' }],
  financeSidebar: [{ type: 'autogenerated', dirName: 'Finance' }],
  propertySidebar: [{ type: 'autogenerated', dirName: 'Property' }],
  referenceSidebar: [{ type: 'autogenerated', dirName: 'Reference / Knowledge' }],
  legalSidebar: [{ type: 'autogenerated', dirName: 'Legal' }],
  workSidebar: [{ type: 'autogenerated', dirName: 'Work & Career' }],
  familySidebar: [{ type: 'autogenerated', dirName: 'Family' }],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
